services:
  - type: web
    name: punchfast
    env: node
    region: oregon
    plan: starter
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: punchfast-db
          property: connectionString
      - key: ADMIN_TOKEN
        sync: false
    healthCheckPath: /api

databases:
  - name: punchfast-db
    region: oregon
    plan: basic-256mb
    databaseName: punchfast
    user: punchfast_user
